
spring:
  servlet:
    multipart:
      # ?? ?? ??
      location: C:/Users/dlaco/Desktop/??/?????/bootcampProject/spring/chapt02-spring_web/chap06-file-upload

      # ?? ??? ?? ??
      max-file-size: 10MB

      # ?? ?? ?? ??
      max-request-size: 10MB
